<?xml version="1.0" encoding="UTF-8"?>
<!--December 16, 2009 -->
<wsdl:definitions
   targetNamespace="http://www.telefonica.com/wsdl/UNICA/SOAP/common/v1/security_headers"
   xmlns:tns="http://www.telefonica.com/wsdl/UNICA/SOAP/common/v1/security_headers" 
   xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
   xmlns:xsd="http://www.w3.org/2001/XMLSchema">

   <wsdl:types>
      <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
			xmlns:uct="http://www.telefonica.com/schemas/UNICA/SOAP/common/v1"
			targetNamespace="http://www.telefonica.com/wsdl/UNICA/SOAP/common/v1/security_headers"
			elementFormDefault="qualified">	
      	
      <xsd:import namespace="http://www.telefonica.com/schemas/UNICA/SOAP/common/v1" schemaLocation="UNICA_API_SOAP_common_types_v1_0.xsd"/>
      
      <xsd:element name="simpleOAuthHeader" type="uct:SimpleOAuthHeaderType"/>
      <xsd:element name="sessionToken" type="uct:SessionTokenType"/>
      
      </xsd:schema>
	
	</wsdl:types>

<!--For access to UNICA APIs with NO Login -->
   <wsdl:message name="SimpleOAuthHeader">
      <wsdl:part name="simpleOAuthHeader" element="tns:simpleOAuthHeader"/>
   </wsdl:message>

<!--For access to UNICA APIs with Login -->
   <wsdl:message name="SessionToken">
      <wsdl:part name="sessionToken" element="tns:sessionToken"/>
   </wsdl:message>
   

</wsdl:definitions>
