
package service.notification;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "NotificationPort", targetNamespace = "http://www.telefonica.com/wsdl/UNICA/SOAP/m2m/notification/v1/services")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface NotificationPort {


    /**
     * 
     * @param subscriptionLogicalName
     * @param eventKind
     * @param xmlRegister
     * @return
     *     returns int
     * @throws ClientException
     * @throws ServerException
     */
    @WebMethod(action = "urn:notify")
    @WebResult(name = "result", targetNamespace = "http://www.telefonica.com/schemas/UNICA/SOAP/m2m/notification/v1/types")
    @RequestWrapper(localName = "notify", targetNamespace = "http://www.telefonica.com/schemas/UNICA/SOAP/m2m/notification/v1/types", className = "service.notification.Notify")
    @ResponseWrapper(localName = "notifyResponse", targetNamespace = "http://www.telefonica.com/schemas/UNICA/SOAP/m2m/notification/v1/types", className = "service.notification.NotifyResponse")
    public int notify(
        @WebParam(name = "subscriptionLogicalName", targetNamespace = "http://www.telefonica.com/schemas/UNICA/SOAP/m2m/notification/v1/types")
        String subscriptionLogicalName,
        @WebParam(name = "eventKind", targetNamespace = "http://www.telefonica.com/schemas/UNICA/SOAP/m2m/notification/v1/types")
        EventKindType eventKind,
        @WebParam(name = "xmlRegister", targetNamespace = "http://www.telefonica.com/schemas/UNICA/SOAP/m2m/notification/v1/types")
        String xmlRegister)
        throws ClientException, ServerException
    ;

}
