
package service.command.response;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CommandResponsePort", targetNamespace = "http://www.telefonica.com/wsdl/UNICA/SOAP/m2m/commandresponse/v1/services")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CommandResponsePort {


    /**
     * 
     * @param errorText
     * @param correlator
     * @param errorCode
     * @param commandResult
     * @return
     *     returns int
     * @throws ClientException
     * @throws ServerException
     */
    @WebMethod(action = "urn:commandSensorResult")
    @WebResult(name = "result", targetNamespace = "http://www.telefonica.com/schemas/UNICA/SOAP/m2m/commandresponse/v1/types")
    @RequestWrapper(localName = "commandSensorResult", targetNamespace = "http://www.telefonica.com/schemas/UNICA/SOAP/m2m/commandresponse/v1/types", className = "service.command.response.CommandSensorResult")
    @ResponseWrapper(localName = "commandSensorResultResponse", targetNamespace = "http://www.telefonica.com/schemas/UNICA/SOAP/m2m/commandresponse/v1/types", className = "service.command.response.CommandSensorResultResponse")
    public int commandSensorResult(
        @WebParam(name = "correlator", targetNamespace = "http://www.telefonica.com/schemas/UNICA/SOAP/m2m/commandresponse/v1/types")
        String correlator,
        @WebParam(name = "commandResult", targetNamespace = "http://www.telefonica.com/schemas/UNICA/SOAP/m2m/commandresponse/v1/types")
        CommandSensorResultType commandResult,
        @WebParam(name = "errorCode", targetNamespace = "http://www.telefonica.com/schemas/UNICA/SOAP/m2m/commandresponse/v1/types")
        int errorCode,
        @WebParam(name = "errorText", targetNamespace = "http://www.telefonica.com/schemas/UNICA/SOAP/m2m/commandresponse/v1/types")
        String errorText)
        throws ClientException, ServerException
    ;

}
