
/*
 * #--------------------------------------------------------------------------
 * # Copyright (c) 2013 VITRO FP7 Consortium.
 * # All rights reserved. This program and the accompanying materials
 * # are made available under the terms of the GNU Lesser Public License v3.0 which accompanies this distribution, and is available at
 * # http://www.gnu.org/licenses/lgpl-3.0.html
 * #
 * # Contributors:
 * #     Antoniou Thanasis (Research Academic Computer Technology Institute)
 * #     Paolo Medagliani (Thales Communications & Security)
 * #     D. Davide Lamanna (WLAB SRL)
 * #     Alessandro Leoni (WLAB SRL)
 * #     Francesco Ficarola (WLAB SRL)
 * #     Stefano Puglia (WLAB SRL)
 * #     Panos Trakadas (Technological Educational Institute of Chalkida)
 * #     Panagiotis Karkazis (Technological Educational Institute of Chalkida)
 * #     Andrea Kropp (Selex ES)
 * #     Kiriakos Georgouleas (Hellenic Aerospace Industry)
 * #     David Ferrer Figueroa (Telefonica Investigación y Desarrollo S.A.)
 * #
 * #--------------------------------------------------------------------------
 */

package service.subscription.response;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "M2MSubscriptionResponseService", targetNamespace = "http://www.telefonica.com/wsdl/UNICA/SOAP/m2m/subscriptionresponse/v1/services", wsdlLocation = "file:/C:/workspace/allProjects/VitroMiddlewareNew/vitroUI/webWS/src/main/resources/UNICA_API_SOAP_m2m_subscriptionresponse_services_v1_1.wsdl")
public class M2MSubscriptionResponseService
    extends Service
{

    private final static URL M2MSUBSCRIPTIONRESPONSESERVICE_WSDL_LOCATION;
    private final static WebServiceException M2MSUBSCRIPTIONRESPONSESERVICE_EXCEPTION;
    private final static QName M2MSUBSCRIPTIONRESPONSESERVICE_QNAME = new QName("http://www.telefonica.com/wsdl/UNICA/SOAP/m2m/subscriptionresponse/v1/services", "M2MSubscriptionResponseService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/workspace/allProjects/VitroMiddlewareNew/vitroUI/webWS/src/main/resources/UNICA_API_SOAP_m2m_subscriptionresponse_services_v1_1.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        M2MSUBSCRIPTIONRESPONSESERVICE_WSDL_LOCATION = url;
        M2MSUBSCRIPTIONRESPONSESERVICE_EXCEPTION = e;
    }

    public M2MSubscriptionResponseService() {
        super(__getWsdlLocation(), M2MSUBSCRIPTIONRESPONSESERVICE_QNAME);
    }

    public M2MSubscriptionResponseService(WebServiceFeature... features) {
        super(__getWsdlLocation(), M2MSUBSCRIPTIONRESPONSESERVICE_QNAME, features);
    }

    public M2MSubscriptionResponseService(URL wsdlLocation) {
        super(wsdlLocation, M2MSUBSCRIPTIONRESPONSESERVICE_QNAME);
    }

    public M2MSubscriptionResponseService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, M2MSUBSCRIPTIONRESPONSESERVICE_QNAME, features);
    }

    public M2MSubscriptionResponseService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public M2MSubscriptionResponseService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SubscriptionResponsePort
     */
    @WebEndpoint(name = "SubscriptionResponse")
    public SubscriptionResponsePort getSubscriptionResponse() {
        return super.getPort(new QName("http://www.telefonica.com/wsdl/UNICA/SOAP/m2m/subscriptionresponse/v1/services", "SubscriptionResponse"), SubscriptionResponsePort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SubscriptionResponsePort
     */
    @WebEndpoint(name = "SubscriptionResponse")
    public SubscriptionResponsePort getSubscriptionResponse(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.telefonica.com/wsdl/UNICA/SOAP/m2m/subscriptionresponse/v1/services", "SubscriptionResponse"), SubscriptionResponsePort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (M2MSUBSCRIPTIONRESPONSESERVICE_EXCEPTION!= null) {
            throw M2MSUBSCRIPTIONRESPONSESERVICE_EXCEPTION;
        }
        return M2MSUBSCRIPTIONRESPONSESERVICE_WSDL_LOCATION;
    }

}
